# Generated by Django 6.0 on 2026-04-08 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Payments"},
        ),
    ]
