# Generated by Django 6.0 on 2026-04-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_refundrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="processed_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
