# Generated by Django 6.0 on 2026-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_refundrequest_processed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Refund Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
