# Generated by Django 6.0 on 2026-08-27 00:33

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


def populate_payment_methods(apps, schema_editor):
    PaymentMethod = apps.get_model("payments", "PaymentMethod")
    Payment = apps.get_model("payments", "Payment")

    paystack_pm, _ = PaymentMethod.objects.get_or_create(
        code="PAYSTACK",
        defaults={"description": "Paystack Payment Gateway", "status": "ACTIVE"},
    )
    PaymentMethod.objects.get_or_create(
        code="CASH_ON_DELIVERY",
        defaults={"description": "Cash on Delivery", "status": "ACTIVE"},
    )
    Payment.objects.all().update(payment_method=paystack_pm)


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_remove_order_payment_method_and_more"),
        ("payments", "0006_alter_refundrequest_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("CASH_ON_DELIVERY", "Cash on Delivery"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Payment Methods",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(
            populate_payment_methods, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name="refundrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Return Requests",
            },
        ),
        migrations.RenameField(
            model_name="refundrequest",
            old_name="requested_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="card_bin",
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="evidence_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_refund_evidence_path
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_requests",
                to="order.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[("PAYSTACK", "Paystack"), ("BANK_TRANSFER", "Bank Transfer")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="refund_receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.get_refund_receipts
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="return_number",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="return_tracking_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refund_requests",
                to="order.order",
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="reason",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Refund Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.paymentmethod",
            ),
        ),
    ]
