# Generated by Django 6.0 on 2026-09-12 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_payment_status_alter_orderitem_order"),
        ("payments", "0007_paymentmethod_alter_refundrequest_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("INITIALIZED", "Initialized"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "return_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "evidence_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.get_refund_evidence_path,
                    ),
                ),
                (
                    "refund_receipt_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.models.get_refund_receipts
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Refund Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "return_tracking_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "return_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="order.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="order.orderitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Return Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="RefundRequest",
        ),
    ]
