# Generated by Django 6.0 on 2026-09-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0008_alter_payment_status_returnrequest_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAYSTACK", "Paystack"),
                    ("CASH_ON_DELIVERY", "Cash on Delivery"),
                ],
                editable=False,
                max_length=50,
                null=True,
            ),
        ),
    ]
