# Generated by Django 6.0 on 2026-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_remove_payment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("UNDER_REVIEW", "Under Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
