# Generated by Django 6.0 on 2026-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_returnrequest_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
