# Generated by Django 6.0 on 2026-10-07 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ("display_order",)},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name_plural": "Categories",
            },
        ),
    ]
