# Generated by Django 6.0 on 2026-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/images"),
        ),
    ]
