# Generated by Django 6.0 on 2026-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_banner_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
        migrations.AddField(
            model_name="banner",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
