# Generated by Django 6.0 on 2026-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_banner_is_active_remove_category_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
            ),
        ),
    ]
