# Generated by Django 6.0 on 2026-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_banner_status_alter_category_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
            ),
        ),
    ]
