# Generated by Django 6.0 on 2025-12-23 17:36

import materials.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        upload_to=materials.models.generated_image_path()
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("premium", "Premium"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=30,
                    ),
                ),
                ("color", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("stock", models.IntegerField()),
            ],
        ),
    ]
