# Generated by Django 6.0 on 2026-06-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0003_alter_materials_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materials",
            old_name="updatred_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="materials",
            name="quality_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LUXURY", "Luxury"),
                    ("PREMIUM", "Premium"),
                    ("REGULAR", "Regular"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
