# Generated by Django 6.0 on 2026-06-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_banner_image"),
        ("materials", "0004_rename_updatred_at_materials_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materials",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target_model__model": "materials"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="material_categories",
                to="core.category",
            ),
        ),
    ]
