# Generated by Django 6.0 on 2026-06-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_materials_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materials",
            name="category",
        ),
    ]
