# Generated by Django 6.0 on 2026-06-25 23:07

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_remove_materials_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=core.models.generated_image_path()),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="materials.materials",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="MaterialSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GLD", "Gold"),
                            ("SLV", "Silver"),
                            ("BGE", "Beige"),
                            ("CRM", "Cream"),
                            ("NVY", "Navy Blue"),
                            ("FGR", "Forest Green"),
                            ("MRN", "Maroon / Wine"),
                            ("BRN", "Brown"),
                            ("PNK", "Pink"),
                            ("PRP", "Purple"),
                            ("GRY", "Grey"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ANK", "Ankara"),
                            ("SLK", "Silk"),
                            ("LAC", "Lace"),
                            ("CHF", "Chiffon"),
                            ("COT", "Cotton"),
                            ("LIN", "Linen"),
                            ("JCQ", "Jacquard"),
                            ("VLV", "Velvet"),
                            ("BRC", "Brocade"),
                            ("ADR", "Adire (Indigo Tie-Dye)"),
                            ("KMP", "Kampala (Multi-color Tie-Dye)"),
                            ("ASO", "Aso Oke"),
                            ("GRG", "George Fabric"),
                            ("AOC", "Akwa Ocha"),
                            ("LAC", "Lace"),
                            ("SEN", "Senator Cashmere"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "key_features",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("thread_count", models.IntegerField(blank=True, null=True)),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLN", "Plain / Solid"),
                            ("FLR", "Floral"),
                            ("STP", "Striped"),
                            ("CHK", "Checked / Plaid"),
                            ("DOT", "Polka Dot"),
                            ("ABS", "Abstract"),
                            ("EMB", "Embroidered"),
                            ("PTN", "Patterned"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_spec",
                        to="materials.materials",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaterialVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="<core.models.generated_image_path object at 0x0000023C35166F30>/videos/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="<core.models.generated_image_path object at 0x0000023C35166F30>/videos/video_thumbnails/",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="materials.materials",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
