# Generated by Django 6.0 on 2026-07-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_materialimages_materialspecification_materialvideo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialspecification",
            name="material",
        ),
        migrations.RemoveField(
            model_name="materialvideo",
            name="material",
        ),
        migrations.RemoveField(
            model_name="materials",
            name="color",
        ),
        migrations.RemoveField(
            model_name="materials",
            name="image",
        ),
        migrations.RemoveField(
            model_name="materials",
            name="stock",
        ),
        migrations.AlterField(
            model_name="materials",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_material",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="MaterialImages",
        ),
        migrations.DeleteModel(
            name="MaterialSpecification",
        ),
        migrations.DeleteModel(
            name="MaterialVideo",
        ),
    ]
