# Generated by Django 6.0 on 2026-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "materials",
            "0009_materialspecification_materialvariant_materialimages_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="materialvariant",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="materialvariant",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLK", "Black"),
                    ("WHT", "White"),
                    ("GLD", "Gold"),
                    ("SLV", "Silver"),
                    ("BGE", "Beige"),
                    ("CRM", "Cream"),
                    ("NVY", "Navy Blue"),
                    ("FGR", "Forest Green"),
                    ("MRN", "Maroon or Wine"),
                    ("BRN", "Brown"),
                    ("PNK", "Pink"),
                    ("PRP", "Purple"),
                    ("GRY", "Grey"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
