# Generated by Django 6.0 on 2026-07-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0010_materialvariant_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materials",
            old_name="is_active",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="materialspecification",
            name="material_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANK", "Ankara"),
                    ("SLK", "Silk"),
                    ("LAC", "Lace"),
                    ("CHF", "Chiffon"),
                    ("COT", "Cotton"),
                    ("LIN", "Linen"),
                    ("JCQ", "Jacquard"),
                    ("VLV", "Velvet"),
                    ("BRC", "Brocade"),
                    ("ADR", "Adire (Indigo Tie-Dye)"),
                    ("KMP", "Kampala (Multi-color Tie-Dye)"),
                    ("ASO", "Aso Oke"),
                    ("GRG", "George Fabric"),
                    ("AOC", "Akwa Ocha"),
                    ("SEN", "Senator Cashmere"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
