# Generated by Django 6.0 on 2026-08-11 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_banner_status_alter_category_display_order_and_more"),
        ("materials", "0011_rename_is_active_materials_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialvariant",
            name="is_active",
        ),
        migrations.AddField(
            model_name="materialvariant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="materialimages",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialimages",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.GeneratedImagePath()
            ),
        ),
        migrations.AlterField(
            model_name="materialimages",
            name="is_primary",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target_model__model": "materials"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materials",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
            ),
        ),
        migrations.AlterField(
            model_name="materials",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="materialspecification",
            name="material",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="materials.materials",
            ),
        ),
        migrations.AlterField(
            model_name="materialvariant",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="materials.materials",
            ),
        ),
        migrations.AlterField(
            model_name="materialvideo",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materialvideo",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.GeneratedVideoPath()
            ),
        ),
    ]
