# Generated by Django 6.0 on 2026-09-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0012_remove_materialvariant_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialvariant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
            ),
        ),
    ]
