# Generated by Django 6.0 on 2026-02-17 13:02

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.generated_image_path()
            ),
        ),
    ]
