# Generated by Django 6.0 on 2026-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customuser_address_customuser_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHERS", "Others")]
            ),
        ),
    ]
