# Generated by Django 6.0 on 2026-02-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Reviews"},
        ),
    ]
