# Generated by Django 6.0 on 2026-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_alter_reviews_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="verified_purchase",
            field=models.BooleanField(default=True),
        ),
    ]
