# Generated by Django 6.0 on 2026-02-11 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Carts"},
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-created_at"], "verbose_name_plural": "CartItems"},
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="material_price",
            new_name="unit_price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_price",
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.BooleanField(default="False"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contenttypes.contenttype",
            ),
        ),
    ]
