# Generated by Django 6.0 on 2026-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
