# Generated by Django 6.0 on 2026-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_cartitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="object_id",
            field=models.UUIDField(),
        ),
    ]
