# Generated by Django 6.0 on 2026-06-21 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cartitem_object_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="updatred_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="updatred_at",
            new_name="updated_at",
        ),
    ]
