# Generated by Django 6.0 on 2026-08-19 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_rename_updatred_at_cart_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="sub_total",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="unit_price",
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
