# Generated by Django 6.0 on 2026-09-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_remove_cart_status_remove_cartitem_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
