# Generated by Django 6.0 on 2026-02-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverymethod",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
