# Generated by Django 6.0 on 2026-02-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_orderitem_sub_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("OUT FOR DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                    ("RETURNED", "Returned"),
                    ("FAILED DELIVERY", "Failed Delivery"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
