# Generated by Django 6.0 on 2026-02-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_delivery_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[("HOME", "Home"), ("WORK", "Work"), ("OTHERS", "Others")],
                default="HOME",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_payment",
                to="order.paymentmethod",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESSFUL", "Successful"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
