# Generated by Django 6.0 on 2026-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_address_address_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="code",
            field=models.CharField(
                choices=[
                    ("PAYSTACK", "Paystack"),
                    ("CASH_ON_DELIVERY", "Cash on Delivery"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
