# Generated by Django 6.0 on 2026-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_order_tracking_id_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sub_total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
    ]
