# Generated by Django 6.0 on 2026-04-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_order_sub_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_discount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
    ]
