# Generated by Django 6.0 on 2026-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_order_total_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SHPPING", "Processing"),
                    ("OUT FOR DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                    ("RETURNED", "Returned"),
                    ("FAILED DELIVERY", "Failed Delivery"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONFIRMED", "Confirmed"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("FAILED", "Failed"),
                    ("RETURNED", "Returned"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
    ]
