# Generated by Django 6.0 on 2026-04-29 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_delivery_status_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverymethod",
            name="estimated_date",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="delivery_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="display_name",
            field=models.CharField(
                choices=[
                    ("PAYSTACK", "Paystack"),
                    ("CASH_ON_DELIVERY", "Cash on Delivery"),
                ],
                max_length=100,
            ),
        ),
    ]
