# Generated by Django 6.0 on 2026-04-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_deliverymethod_estimated_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverymethod",
            name="delivery_time",
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="estimated_date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("STANDARD_DELIVERY", "Standard Delivery"),
                    ("EXPRESS_DELIVERY", "Express Delivery"),
                    ("PREMIUM_DELIVERY", "Premium Delivery"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SHPPING", "Processing"),
                    ("OUT_FOR_DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                    ("RETURNED", "Returned"),
                    ("FAILED_DELIVERY", "Failed Delivery"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
    ]
