# Generated by Django 6.0 on 2026-08-27 00:33

from decimal import Decimal

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_address_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="payment_method",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="discount_amount",
            new_name="discount",
        ),
        migrations.RemoveField(
            model_name="deliverymethod",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="deliverymethod",
            name="is_displayed",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_method",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="address",
            name="alternative_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="is_selected",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], default=False
            ),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="is_selected",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], default=False
            ),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="NGN", max_length=5),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                blank=True, editable=False, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="out_for_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="deliverymethod",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("WAITING TO BE SHIPPED", "Waiting To Be Shipped"),
                    ("SHIPPED", "Shipped"),
                    ("OUT_FOR_DELIVERY", "Out For Delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELED", "Canceled"),
                    ("RETURNED", "Returned"),
                    ("FAILED_DELIVERY", "Failed Delivery"),
                ],
                default="PENDING",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("CONFIRMED", "Confirmed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELED", "Canceled"),
                    ("FAILED", "Failed"),
                ],
                default="CREATED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_items",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
