# Generated by Django 6.0 on 2026-08-27 00:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_remove_order_payment_method_and_more"),
        ("payments", "0007_paymentmethod_alter_refundrequest_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
