# Generated by Django 6.0 on 2026-09-14 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_payment_status_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Addresses"},
        ),
    ]
