# Generated by Django 6.0 on 2026-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_alter_address_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="failed_delivery_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
