# Generated by Django 6.0 on 2026-09-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_order_failed_delivery_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
