# Generated by Django 6.0 on 2026-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
