# Generated by Django 6.0 on 2026-10-03 16:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "quality_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LUXURY", "Luxury"),
                            ("PREMIUM", "Premium"),
                            ("REGULAR", "Regular"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "categories",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"target_model__model": "products"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="core.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ANK", "Ankara"),
                            ("SLK", "Silk"),
                            ("LAC", "Lace"),
                            ("CHF", "Chiffon"),
                            ("COT", "Cotton"),
                            ("LIN", "Linen"),
                            ("JCQ", "Jacquard"),
                            ("VLV", "Velvet"),
                            ("BRC", "Brocade"),
                            ("ADR", "Adire (Indigo Tie-Dye)"),
                            ("KMP", "Kampala (Multi-color Tie-Dye)"),
                            ("ASO", "Aso Oke"),
                            ("GRG", "George Fabric"),
                            ("AOC", "Akwa Ocha"),
                            ("SEN", "Senator Cashmere"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "key_features",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "product_line",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specification",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GLD", "Gold"),
                            ("SLV", "Silver"),
                            ("BGE", "Beige"),
                            ("CRM", "Cream"),
                            ("NVY", "Navy Blue"),
                            ("FGR", "Forest Green"),
                            ("MRN", "Maroon or Wine"),
                            ("BRN", "Brown"),
                            ("PNK", "Pink"),
                            ("PRP", "Purple"),
                            ("GRY", "Grey"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "color")},
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.GeneratedImagePath(),
                    ),
                ),
                ("display_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        choices=[(True, "True"), (False, "False")], default=False
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                            ("52", "Size 52 (52 inches)"),
                            ("54", "Size 54 (54 inches)"),
                            ("56", "Size 56 (56 inches)"),
                            ("58", "Size 58 (58 inches)"),
                            ("60", "Size 60 (60 inches)"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.productvariant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.GeneratedVideoPath(),
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.GeneratedVideoPath(),
                    ),
                ),
                ("display_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
