# Generated by Django 6.0 on 2026-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productvariantsize",
            constraint=models.UniqueConstraint(
                fields=("variant", "size"), name="unique_variant_size"
            ),
        ),
    ]
