# Generated by Django 6.0 on 2026-02-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_products_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
