# Generated by Django 6.0 on 2026-06-21 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_products_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
    ]
