# Generated by Django 6.0 on 2026-06-25 22:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_products_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=core.models.generated_image_path()),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GLD", "Gold"),
                            ("SLV", "Silver"),
                            ("BGE", "Beige"),
                            ("CRM", "Cream"),
                            ("NVY", "Navy Blue"),
                            ("FGR", "Forest Green"),
                            ("MRN", "Maroon / Wine"),
                            ("BRN", "Brown"),
                            ("PNK", "Pink"),
                            ("PRP", "Purple"),
                            ("GRY", "Grey"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ANK", "Ankara"),
                            ("SLK", "Silk"),
                            ("LAC", "Lace"),
                            ("CHF", "Chiffon"),
                            ("COT", "Cotton"),
                            ("LIN", "Linen"),
                            ("JCQ", "Jacquard"),
                            ("VLV", "Velvet"),
                            ("BRC", "Brocade"),
                            ("ADR", "Adire (Indigo Tie-Dye)"),
                            ("KMP", "Kampala (Multi-color Tie-Dye)"),
                            ("ASO", "Aso Oke"),
                            ("GRG", "George Fabric"),
                            ("AOC", "Akwa Ocha"),
                            ("LAC", "Lace"),
                            ("SEN", "Senator Cashmere"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "key_features",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "product_line",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                            ("52", "Size 52 (52 inches)"),
                            ("54", "Size 54 (54 inches)"),
                            ("56", "Size 56 (56 inches)"),
                            ("58", "Size 58 (58 inches)"),
                            ("60", "Size 60 (60 inches)"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_spec",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="<core.models.generated_image_path object at 0x000001EA50E94890>/videos/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="<core.models.generated_image_path object at 0x000001EA50E94890>/videos/video_thumbnails/",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="products.products",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
