# Generated by Django 6.0 on 2026-06-29 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_productimage_productimages_productspecification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AlterField(
            model_name="products",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="<core.models.generated_image_path object at 0x0000019415419520>/videos/video_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                upload_to="<core.models.generated_image_path object at 0x0000019415419520>/videos/"
            ),
        ),
    ]
