# Generated by Django 6.0 on 2026-07-01 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_remove_products_image_alter_products_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productvideo",
            name="product",
        ),
        migrations.RemoveField(
            model_name="products",
            name="stock",
        ),
        migrations.DeleteModel(
            name="ProductImages",
        ),
        migrations.DeleteModel(
            name="ProductSpecification",
        ),
        migrations.DeleteModel(
            name="ProductVideo",
        ),
    ]
