# Generated by Django 6.0 on 2026-07-01 16:40

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productspecification_productvariant_productimages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvideo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.generated_video_path()
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(upload_to=core.models.generated_video_path()),
        ),
    ]
