# Generated by Django 6.0 on 2026-07-01 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_alter_productvideo_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant",
                to="products.products",
            ),
        ),
    ]
