# Generated by Django 6.0 on 2026-07-02 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_productvariant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLK", "Black"),
                    ("WHT", "White"),
                    ("GLD", "Gold"),
                    ("SLV", "Silver"),
                    ("BGE", "Beige"),
                    ("CRM", "Cream"),
                    ("NVY", "Navy Blue"),
                    ("FGR", "Forest Green"),
                    ("MRN", "Maroon or Wine"),
                    ("BRN", "Brown"),
                    ("PNK", "Pink"),
                    ("PRP", "Purple"),
                    ("GRY", "Grey"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant",
                to="products.products",
            ),
        ),
    ]
