# Generated by Django 6.0 on 2026-07-22 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_productvariant_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="is_active",
            new_name="status",
        ),
    ]
