# Generated by Django 6.0 on 2026-08-06 10:57

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_rename_is_active_products_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="is_active",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.models.generated_image_path()
            ),
        ),
        migrations.AlterField(
            model_name="productimages",
            name="is_primary",
            field=models.BooleanField(
                choices=[(True, "True"), (False, "False")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="material_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ANK", "Ankara"),
                    ("SLK", "Silk"),
                    ("LAC", "Lace"),
                    ("CHF", "Chiffon"),
                    ("COT", "Cotton"),
                    ("LIN", "Linen"),
                    ("JCQ", "Jacquard"),
                    ("VLV", "Velvet"),
                    ("BRC", "Brocade"),
                    ("ADR", "Adire (Indigo Tie-Dye)"),
                    ("KMP", "Kampala (Multi-color Tie-Dye)"),
                    ("ASO", "Aso Oke"),
                    ("GRG", "George Fabric"),
                    ("AOC", "Akwa Ocha"),
                    ("SEN", "Senator Cashmere"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="display_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=core.models.generated_video_path()
            ),
        ),
    ]
