# Generated by Django 6.0 on 2026-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_remove_productvariant_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")]
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")], default=False
            ),
        ),
    ]
