# Generated by Django 6.0 on 2026-08-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_banner_status_alter_category_display_order_and_more"),
        ("products", "0018_alter_products_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="categories",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"target_model__model": "products"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="core.category",
            ),
        ),
    ]
