# Generated by Django 6.0 on 2026-10-01 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_productvariantsize"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "color")},
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="price_adjustment",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="size",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock",
        ),
    ]
